services:
  csharpapp:
    build: ./dotnet-api
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./dotnet-api
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  php:
    build: ./symfony-api
    volumes:
      - ./symfony-api/:/var/www/html
      - ./symfony-api/extraconf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db

  web:
    image: nginx:latest
    volumes:
      - ./symfony-api/:/var/www/html
      - ./symfony-api/extraconf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - php

  vue-app:
    build: ./vuejs-app
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./vuejs-app
    ports:
      - "8082:80"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "2000:80"

volumes:
  pgdata: {}
